### ISSUE TITLE
Pre-configured problems

### ISSUE THREAD

**Issue by dscntr17** [ruraj/beginners#4]
Hello,

I'm very new to Java and Github.  I'm learning as I'm going.  I checked out the "sorter" level that I want to work on, however I don't see the pre-configured problems in Intelli J.  I know I have done something wrong, but I'm not sure what I did.  I'm new to Intelli J also.  Where do I find the pre-configured problems?

Thank you

**Comment by ruraj** [comment]
Were you able to load the project? Instead of trying to load the individual problem `gradle.build` file, load the root project. Let me know if you need more help!

**Comment by dscntr17** [comment]
I was able to load all of the files and folders on git and intellij.  If that's what you mean.
